export interface FuturesDetail {
  symbol: string
  displayName: string
  displayNameEn: string
  positionOpenType: 1 | 2 | 3 // position open type,1：isolated，2：cross，3：both
  baseCoin: string
  quoteCoin: string
  baseCoinName: string
  quoteCoinName: string
  futureType: 1
  settleCoin: string
  contractSize: number
  minLeverage: number
  maxLeverage: number
  countryConfigContractMaxLeverage: number
  priceScale: number
  volScale: number
  amountScale: number
  priceUnit: number
  volUnit: number
  minVol: number
  maxVol: number
  bidLimitPriceRate: number
  askLimitPriceRate: number
  takerFeeRate: number
  makerFeeRate: number
  maintenanceMarginRate: number
  initialMarginRate: number
  riskBaseVol: number
  riskIncrVol: number
  riskLongShortSwitch: number
  riskIncrMmr: number
  riskIncrImr: number
  riskLevelLimit: number
  priceCoefficientVariation: number
  indexOrigin: string[]
  state: 0
  isNew: boolean
  isHot: boolean
  isHidden: boolean
  conceptPlate: string[]
  conceptPlateId: number[]
  riskLimitType: string
  maxNumOrders: number[]
  marketOrderMaxLevel: number
  marketOrderPriceLimitRate1: number
  marketOrderPriceLimitRate2: number
  triggerProtect: number
  appraisal: number
  showAppraisalCountdown: number
  automaticDelivery: number
  apiAllowed: boolean
  depthStepList: string[]
  limitMaxVol: number
  threshold: number
  baseCoinIconUrl: string
  id: number
  vid: string
  baseCoinId: string // !!!
  createTime: number
  openingTime: number
  openingCountdownOption: number
  showBeforeOpen: boolean
  isMaxLeverage: boolean
  isZeroFeeRate: boolean
  riskLimitMode: string
  isZeroFeeSymbol: boolean
  riskLimitCustom: {
    level: number
    maxVol: number
    mmr: number
    imr: number
    maxLeverage: number
  }[]
  liquidationFeeRate: number
  feeRateMode: string
  leverageFeeRates: []
  symbolFeeRateMode: string
  symbolTakerFeeRate: number
  symbolMakerFeeRate: number
}
